export interface AIEstimatedQuestionScoreDto {
  countryID: number;
  pillarID: number;
  questionID: number;
  questionText: string;
  year: number;
  aiScore: number | null;
  aiProgress: number | null;
  evaluatorScore: number | null;
  discrepancy: number | null;
  confidenceLevel: string | null;
  sourcesConsulted: number | null;
  evidenceSummary: string | null;
  structuralEvidence: string | null;
  operationalEvidence: string | null;
  outcomeEvidence: string | null;
  perceptionEvidence: string | null;
  temporalReliability: string | null;
  relationalDependencies: string | null;
  stressGeopoliticalShock: string | null;
  stressEconomicShock: string | null;
  stressFinanceShock: string | null;
  dataOpacityRisk: string | null;
  redFlag: string | null;
  sourceType: string | null;
  sourceName: string | null;
  sourceURL: string | null;
  sourceDataYear: number | null;
  sourceDataExtract: string | null;
  sourceHierarchyLevel: number | null;
  updatedAt: Date | null;
}
